### PR TITLE
added the footer

### PR DESCRIPTION
**Pull request by thePlebDev**
Quizzer
Added a carousel to the footer, thought it looked nice. The carousel contains all the contributors names and the links to their personal websites or github account. The array in the footer will allow for future developers to easily become part of the carousel

### CODE REVIEW

**Comment by Souvikns** [comment]
@thePlebDev could you attach a screenshot of the component that you have built

**Comment by thePlebDev** [comment]
@Souvikns added the pic

**Comment by Souvikns** [comment]
About the contributors I was thinking we have the reademe file where all the contributors are featured, or we could build another page featuring all the contributors with images and links. I think we having contributors in footer make the design bloated. 
> I am open to any suggestion

**Comment by thePlebDev** [comment]
ok, youre the boss. Ill see what else I can put in the footer

**Comment by thePlebDev** [comment]
Quizz

what about this?

**Comment by Souvikns** [comment]
This design looks fine, you can go with this

**Pull request merged**
